server:
  openai_server_engine: vajra
  openai_api_url: "http://localhost:8000/v1"
  openai_api_port: 8000
  openai_api_key: token-abc123
  fixed_chunk_size: 512
  min_chunk_size: 1
  max_chunk_size: 512
  schedule_policy: fcfs
  scheduler_config: FIXED_CHUNK

model:
  name: llama-3-8b
  identifier: meta-llama/Meta-Llama-3-8B
  chat_template: "{% set loop_messages = messages %}{% for message in loop_messages %}{% set content = '<|start_header_id|>' + message['role'] + '<|end_header_id|>\n\n'+ message['content'] | trim + '<|eot_id|>' %}{% if loop.index0 == 0 %}{% set content = bos_token + content %}{% endif %}{{ content }}{% endfor %}{{ '<|start_header_id|>assistant<|end_header_id|>\n\n' }}"

parallel_spec:
  tp_dimension: 1
  pp_dimension: 1

request_generator_config:
  start_qps: 1
  request_interval_generator_provider: "poisson"
  request_length_generator_provider: "trace"
  trace_request_length_generator_trace_file: "data/processed_traces/sharegpt_8k_stats_llama2_tokenizer_filtered_v2.csv"
  trace_file_name: "arxiv"

request_config:
  num_clients: 2
  num_concurrent_requests_per_client: 2
  timeout: 1200
  max_num_completed_requests: 10
  additional_sampling_params: {}
  llm_api: "openai_chat"
  request_generator_max_tokens: 8192

benchmark_config:
  output_dir: "results/benchmark_vajra_llama-8B_tp_1"
  qps: 5.0
  should_use_given_dir: true