# SGLang Server Configuration
module: "sglang.launch_server"
port: 8004
model_path: "meta-llama/Meta-Llama-3-8B-Instruct"
dtype: "auto"
tensor_parallel_size: 1
enable_cache_telemetry: true
cache_telemetry_output_dir: "../veeksha/sgl-cache-tp1-hiradix-conv-wts"
enable_hierarchical_cache: true
reset_cache_telemetry_on_new_file: true
context_length: 128000
max_running_requests: 256
chunked_prefill_size: 512
page_size: 16
json_model_override_args: {'rope_scaling': {'type': 'linear', 'factor': 16.0}, 'rope_theta': 8000000}
mem_fraction_static: 0.5