seed: 42
output_dir: benchmark_output/qwen3_omni

client:
  type: openai_chat_completions
  api_base: "http://localhost:8091/v1/"
  api_key: "EMPTY"
  model: Qwen/Qwen3-Omni-30B-A3B-Instruct
  request_timeout: 300
  ignore_eos: false
  max_tokens_param: null
  additional_sampling_params: '{"modalities": ["audio"], "sampling_params_list": [{"temperature": 0.4, "top_p": 0.9, "top_k": 1, "max_tokens": 16384, "repetition_penalty": 1.05, "stop_token_ids": [151645], "seed": 42}, {"temperature": 0.9, "top_k": 50, "max_tokens": 4096, "seed": 42, "detokenize": false, "repetition_penalty": 1.05, "stop_token_ids": [2150]}, {"temperature": 0.0, "top_p": 1.0, "top_k": -1, "max_tokens": 65536, "seed": 42, "detokenize": true, "repetition_penalty": 1.1}]}'

session_generator:
  type: trace
  trace_file: traces/sharegpt_data.json
  wrap_mode: true
  flavor:
    type: sharegpt
    assistant_role: gpt
    min_tokens: 20
    max_tokens: 150

traffic_scheduler:
  type: concurrent
  target_concurrent_sessions: 1
  rampup_seconds: 0

evaluators:
  - type: performance
    target_channels: ["audio"]
    audio_channel:
      save_audio_files: true
    stream_metrics: true
    stream_metrics_interval: 5.0
    slos:
      - name: "P99 TTFA under 500ms"
        metric: ttfa
        percentile: 0.99
        value: 1000
        type: constant
      - name: "P90 Total Latency under 2s"
        metric: e2e
        percentile: 0.90
        value: 4000
        type: constant

runtime:
  max_sessions: 100
  benchmark_timeout: 30000
  num_client_threads: 1
  num_dispatcher_threads: 1
  num_completion_threads: 1

trace_recorder:
  enabled: false

wandb:
  enabled: true
  project: "sharegpt-tts"
  run_name: "qwen3_omni"
  tags: ["vllm-omni", "qwen3-omni"]
  log_artifacts: true
