name: "Run linter"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
defaults:
  run:
    shell: bash -l {0}
jobs:
  sanity_check:
    runs-on: [self-hosted, cpu]
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Build CI image"
        run: docker build -t veeksha-lint .
      - name: "Run lint container"
        run: |
          docker run -d \
          -w /repo \
          --name veeksha-lint-${{ github.run_id }} \
          veeksha-lint sleep infinity
      - name: "Install dependencies"
        run: |
          docker exec \
          veeksha-lint-${{ github.run_id }} \
          bash -lc "make test/setup/314"
      - name: "Run all lint checks"
        run: |
          docker exec \
          veeksha-lint-${{ github.run_id }} \
          bash -lc "source .venv314/bin/activate && make lint"
      - name: "Stop Docker container"
        if: always()
        run: |
          docker stop veeksha-lint-${{ github.run_id }}
          docker rm veeksha-lint-${{ github.run_id }}
