name: "Run linter"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
defaults:
  run:
    shell: bash -l {0}
jobs:
  sanity_check:
    runs-on: [self-hosted, cpu]
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Run lint"
        run: |
          docker run --rm \
          -v "${GITHUB_WORKSPACE}:/repo" \
          -w /repo \
          ghcr.io/astral-sh/uv:bookworm \
          bash -c "uv venv --python 3.14t .venv && source .venv/bin/activate && uv pip install -e . --group dev && make lint"
